using Bitstamp.Net.Objects.Models;
using Bitstamp.Net.Objects.Models.Socket;
using System.Text.Json.Serialization;

namespace Bitstamp.Net.Converters
{
    [JsonSerializable(typeof(BitstampWithdrawId))]
    [JsonSerializable(typeof(BitstampOrderEvent[]))]
    [JsonSerializable(typeof(BitstampLeverageSetting))]
    [JsonSerializable(typeof(BitstampLeverageSetting[]))]
    [JsonSerializable(typeof(BitstampCollateralAsset[]))]
    [JsonSerializable(typeof(BitstampMarginInfo))]
    [JsonSerializable(typeof(BitstampSettleTransaction[]))]
    [JsonSerializable(typeof(BitstampPosition))]
    [JsonSerializable(typeof(BitstampClosePositionsResponse))]
    [JsonSerializable(typeof(BitstampPositionHistory[]))]
    [JsonSerializable(typeof(BitstampPosition))]
    [JsonSerializable(typeof(BitstampPosition[]))]
    [JsonSerializable(typeof(BitstampMarginTiers[]))]
    [JsonSerializable(typeof(BitstampCryptoDeposit[]))]
    [JsonSerializable(typeof(BitstampCryptoTransactions))]
    [JsonSerializable(typeof(BitstampDepositAddress))]
    [JsonSerializable(typeof(BitstampFiatWithdrawalStatus))]
    [JsonSerializable(typeof(BitstampWithdrawal[]))]
    [JsonSerializable(typeof(BitstampCancelWithdrawResponse))]
    [JsonSerializable(typeof(BitstampMaxTradeQuantity))]
    [JsonSerializable(typeof(BitstampAccountSymbol[]))]
    [JsonSerializable(typeof(BitstampReplaceResponse))]
    [JsonSerializable(typeof(BitstampCancelAllOrderResponse))]
    [JsonSerializable(typeof(BitstampWithdrawFee))]
    [JsonSerializable(typeof(BitstampWithdrawFee[]))]
    [JsonSerializable(typeof(BitstampFundingRateHistoryWrapper))]
    [JsonSerializable(typeof(BitstampFundingRate))]
    [JsonSerializable(typeof(BitstampConversionRate))]
    [JsonSerializable(typeof(BitstampTrade[]))]
    [JsonSerializable(typeof(BitstampKlinesResult))]
    [JsonSerializable(typeof(BitstampSymbol[]))]
    [JsonSerializable(typeof(BitstampAsset[]))]
    [JsonSerializable(typeof(BitstampTicker[]))]
    [JsonSerializable(typeof(BitstampTicker))]
    [JsonSerializable(typeof(BitstampKline[]))]
    [JsonSerializable(typeof(BitstampOrderBookUpdate))]
    [JsonSerializable(typeof(BitstampTradingFees[]))]
    [JsonSerializable(typeof(BitstampTradingFees))]
    [JsonSerializable(typeof(BitstampCancelOrderResponse))]
    [JsonSerializable(typeof(BitstampOrder))]
    [JsonSerializable(typeof(BitstampOpenOrder[]))]
    [JsonSerializable(typeof(BitstampAccountBalance[]))]
    [JsonSerializable(typeof(BitstampAsset[]))]
    [JsonSerializable(typeof(BitstampSocketAuthToken))]
    [JsonSerializable(typeof(BitstampUserTransaction[]))]

    [JsonSerializable(typeof(BitstampSocketData<BitstampOrderUpdate>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampErrorData>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampSubscriptionData>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampOrderUpdate>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampOrderBookUpdate>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampTradeUpdate>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampUserTradeUpdate>))]
    [JsonSerializable(typeof(BitstampSocketData<BitstampFundingRateUpdate>))]

    [JsonSerializable(typeof(IDictionary<string, object>))]
    [JsonSerializable(typeof(string))]
    [JsonSerializable(typeof(string[]))]
    [JsonSerializable(typeof(bool))]
    internal partial class BitstampSourceGenerationContext : JsonSerializerContext
    { }
}
